### ISSUE TITLE
gonimo open source baby monitor

### ISSUE THREAD

**Issue by eskimor** [brarcher/protect-baby-monitor#25]
Hi there!

I just discovered your project, which is very similar to my own, [gonimo](https://gonimo.com). It is based on webrtc and currently a WebApp only. We plan on releasing an Android and iOS version too. I thought you might be interested, that there exists some friendly competition.

We are of course also on [github](https://github.com/gonimo/gonimo)!

I will definitely check out your solution! ;-)

**Comment by brarcher** [comment]
Thanks for the poke. I wish you the best in your application!

**Comment by eskimor** [comment]
Good luck with your's too! I tried it out and it seems to work well. I already suggested protect-baby-monitor to someone interested in using Gonimo in a LAN only setup (which is not possible right now).
