### ISSUE TITLE
Settings feature not working in protect baby monitor

### ISSUE THREAD

**Issue by sahmmie** [brarcher/protect-baby-monitor#35]
#### Expected behavior
i launched protect baby monitor, selected use as child device, tap on a 3 dotted icon which is the more options button, then click settings, so I can configure it.

#### Actual behavior
when i clicked the use as child device, i touched the settings button but nothing happened, didnt bring the setting features out.

#### How to reproduce
[download](https://f-droid.org/packages/protect.babymonitor/)

launch protect baby monitor,
click use as child device,
click the 3 dotted button by the right ,
then click the settings

Device Used: Infinix Note 3 or Infinix X601
Operating system: Android 7.0 Nougat
App version: 0.3 (3) - Added on 2018-02-20

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/9p8GmYrIpIw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@sahmmie/settings-feature-not-working-in-protect-baby-monitor">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by brarcher** [comment]
I appreciate the detailed bug report, thanks!

What is Utopian.io? I looked it up and all I see is it "rewards" contributions. What does the platform do?

As for the bug, I think that having the Setting menu option was an oversight. There are no settings to change. I'll remove the Setting menu option.

**Comment by brarcher** [comment]
The unneeded Setting menu has been removed. This fix will appear in a future release.
