### ISSUE TITLE
Joining forces maybe

### ISSUE THREAD

**Issue by Arnaudv6** [brarcher/protect-baby-monitor#37]
Hey, I like the goal of protect-baby-monitor, just have you heard about
https://github.com/ivadim/fruitnanny
Do you think you can share with each other?

**Comment by brarcher** [comment]
I've not heard about the fruitnanny before. Interesting project.

The technologies for this Android application and the fruitnanny are different, and I do not think that they could directly share. Currently, I working on a few other projects and likely will not get involved with the fruitnanny project. Thanks for pointing out the project.
