### ISSUE TITLE
"Discover Child on Network" feature doesn't work

### ISSUE THREAD

**Issue by pieqq** [brarcher/protect-baby-monitor#41]
Hello and thanks for developing this app!

I tested it and found a few issues.

# App/devices info

ProtectBabyMonitor v0.3 (downloaded from F-Droid)
Devices:
- Samsung Galaxy S7 edge (Android 8.0.0)
- Oneplus One (Android 6.x)

Both devices are connected to the same network.

# Steps
1. Start the app on both devices (Samsung = parent device, Oneplus = child device)
2. On the parent device, click `Discover Child on Network`

# Expected result
The child device is shown.

# Actual result
Nothing shows up, no matter how long I wait.

# Additional information
The `Select Child by Address` works fine.

I have another Samsung Galaxy S7 edge (also running Android 8.0.0). If I replace the child device (Oneplus One) with this Samsung Galaxy S7 edge and set it to be a child device, I still cannot see it when clicking `Discover Child on Network`.

Please let me know what kind of logs I can attach, and how (I'm pretty tech-savvy but I'm not very familiar with Android development).

**Comment by pieqq** [comment]
Hmmm... after retrying tonight, with the same devices, it works! I can now see the child device by clicking on `Discover Child on Network`. Marking as closed.

**Comment by brarcher** [comment]
The discovery works by using the mDNS library in Android (though it is called something else). I've seen that the library is a bit finicky in the past, so I would not be surprised if sometimes it does not work. If the issue happens again you are welcome to grab adb logs and I can take a look.
