### ISSUE TITLE
Document stream to linux

### ISSUE THREAD

**Issue by y0va** [brarcher/protect-baby-monitor#50]
I found protect baby monitor quite useful to play android audio stream on linux. 

    ffplay -i tcp://$HOST:$PORT -f s16le -ac 1 -ar 11025

Maybe this should be noted in the documentation.

**Comment by brarcher** [comment]
Cool! Glad the app was useful.

The audio format which is sent between phones is not documented as it is more of an implementation detail. I think having your example available here will be good for others to find, though.

Thanks for sharing
